# Kubernetes profile overrides
quarkus.mongodb.connection-string=mongodb://${PRICING_DB_USERNAME}:${PRICING_DB_PASSWORD}@pricing-service-db:27017/${PRICING_DB_NAME}?authSource=admin

rabbitmq-host=rabbitmq
rabbitmq-port=5672

quarkus.oidc.auth-server-url=http://keycloak:8080/realms/service-app-realm

# Health probes for k8s liveness/readiness
quarkus.smallrye-health.liveness-path=/actuator/health/live
quarkus.smallrye-health.readiness-path=/actuator/health/ready

# Metrics
quarkus.management.enabled=true